
let MOVE_DISTANCE = 10;
let REFRESH_RATE = 100;
let MULTIPLIER = 0.1;
let ENEMY_SPAWN_TIME = 2000;
let HEALTH_SPAWN_TIME = 2000;

export {
    MOVE_DISTANCE,
    REFRESH_RATE,
    MULTIPLIER,
    ENEMY_SPAWN_TIME,
    HEALTH_SPAWN_TIME
}